[project]
name = "mlops-services"
version = "0.1.0"
description = "MLOps Backend"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ['pandas','u8darts','dvc','mlflow==2.22','python-dotenv']
