[project]
name = "mlops-services"
version = "0.1.0"
description = "MLOps Backend"
readme = "README.md"
requires-python = "==3.12.0"
dependencies = ['polars','u8darts','dvc','python-dotenv','mlflow-skinny==2.22.0','influxdb-client']
